import { FormModel } from './formModel';
import * as Yup from 'yup';

const {
  formField: {
    showStoreLogo,
    storeLogo,
    showReceiptName,
    receiptName,
    showStoreName,
    storeName,
    showDiscount,
    showTax,
    showPaidBy,
    showVatNumber,
    showTaxCalculation,
    showCashier,
    duplicatePrint,
    printOnParked,
    showStoreAddress,
    showCity,
    showWebAddress,
    webAddress,
  },
} = FormModel;
export const validationSchema = Yup.object().shape({
  [showStoreLogo.name]: Yup.boolean(),
  [storeLogo.name]: Yup.string(),
  [showReceiptName.name]: Yup.boolean(),
  [receiptName.name]: Yup.string(),
  [showStoreName.name]: Yup.boolean(),
  [storeName.name]: Yup.string(),
  [showDiscount.name]: Yup.boolean(),
  [showTax.name]: Yup.boolean(),
  [showPaidBy.name]: Yup.boolean(),
  [showVatNumber.name]: Yup.boolean(),
  [showTaxCalculation.name]: Yup.boolean(),
  [showCashier.name]: Yup.boolean(),
  [duplicatePrint.name]: Yup.boolean(),
  [printOnParked.name]: Yup.boolean(),
  [showStoreAddress.name]: Yup.boolean(),
  [showCity.name]: Yup.boolean(),
  [showWebAddress.name]: Yup.boolean(),
  [webAddress.name]: Yup.string(),
});

export const formInitialValues = {
  [showStoreLogo.name]: false,
  [storeLogo.name]: 'Select File',
  [showReceiptName.name]: false,
  [receiptName.name]: 'Enter...',
  [showStoreName.name]: false,
  [storeName.name]: 'Enter...',
  [showDiscount.name]: false,
  [showTax.name]: false,
  [showPaidBy.name]: false,
  [showVatNumber.name]: false,
  [showTaxCalculation.name]: false,
  [showCashier.name]: false,
  [duplicatePrint.name]: false,
  [printOnParked.name]: false,
  [showStoreAddress.name]: false,
  [showCity.name]: false,
  [showWebAddress.name]: false,
  [webAddress.name]: 'Enter Url...',
};
