const Tabs = [
  {
    id: "general",
    label: "General",
    classes: "active",
    actions: true,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Total Discount", value: "Group product" },
      { name: "Approved Customers", value: "125456" },
      { name: "Customer Approval Check", value: "HS Code 1" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
    ],
    image: {
      src: "assets/images/product-thumb.jpg",
      class: "img-fluid",
      alt: "",
    },
  },
  {
    id: "purchase",
    label: "Purchase",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
    ],
    image: {},
  },
  {
    id: "sell",
    label: "Sell",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Total Discount", value: "Group product" },
      { name: "Approved Customers", value: "125456" },
      { name: "Customer Approval Check", value: "HS Code 1" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
    ],
    image: {},
  },
  {
    id: "inventory",
    label: "Inventory",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
    ],
    image: {},
  },
  {
    id: "attributes",
    label: "Attributes",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Total Discount", value: "Group product" },
      { name: "Approved Customers", value: "125456" },
      { name: "Customer Approval Check", value: "HS Code 1" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
    ],
    image: {},
  },
  {
    id: "product-variants",
    label: "Product Variants",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Total Discount", value: "Group product" },
      { name: "Approved Customers", value: "125456" },
      { name: "Customer Approval Check", value: "HS Code 1" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
    ],
    image: {},
  },
  {
    id: "financial-dimension",
    label: "Financial Dimension",
    classes: "",
    actions: false,
    tableData: [
      { name: "Sale Unit", value: "FR-1254" },
      { name: "Sale Tax Group", value: "Nujgd" },
      { name: "Base Sale Price", value: "VI-3434T5" },
      { name: "Latest Sale Price", value: "Kutruma" },
      { name: "Sale Single Charges", value: "Qadeem" },
      { name: "Sale Multi Charges", value: "Location group" },
      { name: "Sale Single Discount", value: "KK-Kutruma" },
      { name: "Sale Multi Discount", value: "T-Group" },
      { name: "Sale Total Discount", value: "Group product" },
      { name: "Approved Customers", value: "125456" },
      { name: "Customer Approval Check", value: "HS Code 1" },
      { name: "Sale Price Group", value: "CPCT1-67657" },
      { name: "Customer Rebate", value: "Active" },
      { name: "Sale Price Included Tax", value: "C-Pondt" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
      { name: "Installments", value: "5665" },
    ],
    image: {},
  },
];

export default Tabs;
